import type { TranslationTree } from './types.ts';

export const ar: TranslationTree = {
  common: { all: 'الكل', yes: 'نعم', no: 'لا', active: 'نشط', archived: 'مؤرشف', ready: 'جاهز', none: '—', search: 'بحث...', language: 'اللغة', automatic: 'تلقائي — لغة المتصفح' },
  nav: { operation: 'التشغيل', startupTests: 'اختبارات البدء', banks: 'بنوك التغريدات', queue: 'قائمة الانتظار', sessions: 'الجلسات', history: 'السجل', analytics: 'التحليلات', diagnostics: 'التشخيص', workspaces: 'مساحات العمل', settings: 'الإعدادات' },
  actions: { start: 'بدء', pause: 'إيقاف مؤقت', resume: 'استئناف', stop: 'إيقاف', cancel: 'إلغاء', save: 'حفظ', delete: 'حذف', edit: 'تعديل', open: 'فتح', refresh: 'تحديث', retry: 'إعادة المحاولة', skip: 'تخطي', archive: 'أرشفة', restore: 'استعادة', export: 'تصدير', import: 'استيراد', confirm: 'تأكيد', previous: 'السابق', next: 'التالي', close: 'إغلاق', run: 'تشغيل', add: 'إضافة', extract: 'استخراج' },
  statuses: { IDLE: 'خامل', SCHEDULED: 'مجدولة', RUNNING: 'قيد التشغيل', PAUSED: 'متوقف مؤقتًا', STOPPED: 'متوقف', WAITING: 'في الانتظار', COMPLETED: 'مكتمل', FAILED: 'فشل', PENDING: 'قيد الانتظار', OPENING: 'جارٍ الفتح', READY: 'جاهز', PUBLISHING: 'جارٍ النشر', PUBLISHED: 'تم النشر', PUBLISHED_UNVERIFIED: 'تم النشر — غير مؤكد', SKIPPED: 'تم التخطي', NOT_REQUIRED: 'غير مطلوب', CONNECTED: 'متصل', DISCONNECTED: 'غير متصل', OK: 'سليم', WARN: 'تحذير', FAIL: 'فشل' },
  errors: { dailyPostLimitReached: 'لقد وصلت إلى الحد الأقصى لعدد المنشورات اليومية', unknown: 'حدث خطأ غير متوقع', invalidJson: 'ملف JSON غير صالح', loginRequired: 'يلزم تسجيل الدخول إلى X', publishControlsNotReady: 'عناصر النشر غير جاهزة' },
  settings: { title: 'الإعدادات', interval: 'الفاصل بالدقائق', maxRetries: 'الحد الأقصى لمحاولات الإعادة', timezone: 'المنطقة الزمنية', duplicatePolicy: 'سياسة التكرار', notifications: 'تفعيل إشعارات الأحداث المهمة', confirmBeforeStart: 'تأكيد قبل بدء قائمة الانتظار', keepAutomationTabOpen: 'إبقاء تبويب الأتمتة مفتوحًا', closeTabOnComplete: 'إغلاق التبويب عند اكتمال قائمة الانتظار', language: 'اللغة', globalDefaults: 'الإعدادات العامة الافتراضية', workspaceOverride: 'حفظ كإعداد خاص لمساحة العمل', clearOverride: 'استخدام الإعدادات العامة' },
  operation: { title: 'لوحة التشغيل', currentTweet: 'التغريدة الحالية', publishingCenter: 'مركز التحكم بالنشر', published: 'تم النشر', remaining: 'متبقٍ', failed: 'فشل', skipped: 'تم التخطي', startAt: 'بدء الجلسة في', nextTweetAfter: 'التغريدة التالية بعد', currentItem: 'العنصر الحالي', readyToRun: 'جاهز للتشغيل', engineRunning: 'المحرك يعمل الآن', pausedHint: 'قائمة الانتظار متوقفة مؤقتًا — اضغط استئناف للمتابعة' },
  queue: { title: 'قائمة الانتظار', empty: 'لا توجد عناصر مطابقة للبحث الحالي.', pageSize: 'عرض في الصفحة', selectPage: 'تحديد عناصر الصفحة', selected: 'محدد', clearCompleted: 'مسح المكتمل', item: 'عنصر', items: 'عناصر', page: 'صفحة', of: 'من', bank: 'بنك التغريدات' },
  banks: { title: 'بنوك التغريدات', add: 'إضافة بنك', extract: 'استخراج المحدد', refreshDiff: 'تحديث ومقارنة', temporaryUrl: 'رابط مؤقت لبنك غير محفوظ', noMatch: 'لا توجد بنوك مطابقة للبحث الحالي.', active: 'نشط', replace: 'استبدال العناصر غير المنفذة', append: 'إضافة روابط جديدة فقط' },
  tests: { title: 'اختبارات البدء', validation: 'التحقق من الجاهزية', preflight: 'فحص الجاهزية', dryRun: 'اختبار تجريبي دون نشر', runPreflight: 'فحص الآن', testFirst: 'اختبار أول عنصر', testQueue: 'اختبار القائمة كاملة', stopTest: 'إيقاف الاختبار', noPost: 'يفحص Composer وزر النشر دون الضغط عليه أو زيادة المحاولات' },
  analytics: { title: 'لوحة التحليلات', totalSessions: 'إجمالي الجلسات', totalPosts: 'إجمالي المنشورات', published: 'تم النشر', failed: 'فشل', skipped: 'تم التخطي', successRate: 'نسبة النجاح', averageAttempts: 'متوسط المحاولات', duration: 'متوسط مدة الجلسة', mostActiveBank: 'أكثر بنك نشاطًا', lastActivity: 'آخر نشاط', allXpilot: 'كل X-Pilot' },
  diagnostics: { title: 'مركز التشخيص', run: 'تشغيل التشخيص', readOnly: 'فحص للقراءة فقط دون نشر أو تغيير البيانات', extensionVersion: 'إصدار الإضافة', storageSchema: 'مخطط التخزين', activeWorkspace: 'مساحة العمل النشطة', automationWorkspace: 'مساحة أتمتة النشر', runningSession: 'الجلسة الجارية', alarm: 'Alarm', automationTab: 'تبويب الأتمتة', completed: 'اكتمل التشخيص للقراءة فقط — لم يتم تنفيذ أي نشر' },
  workspaces: { title: 'كل مساحات العمل', active: 'مساحة العمل النشطة', new: 'مساحة عمل جديدة', noDescription: 'لا يوجد وصف', running: 'يعمل الآن', ready: 'جاهز', lastActivity: 'آخر نشاط' },
};
