import type { TranslationTree } from './types.ts';

export const en: TranslationTree = {
  common: { all: 'All', yes: 'Yes', no: 'No', active: 'Active', archived: 'Archived', ready: 'Ready', none: '—', search: 'Search...', language: 'Language', automatic: 'Automatic — Browser language' },
  nav: { operation: 'Operation', startupTests: 'Startup Tests', banks: 'Tweet Banks', queue: 'Queue', sessions: 'Sessions', history: 'History', analytics: 'Analytics', diagnostics: 'Diagnostics', workspaces: 'Workspaces', settings: 'Settings' },
  actions: { start: 'Start', pause: 'Pause', resume: 'Resume', stop: 'Stop', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', open: 'Open', refresh: 'Refresh', retry: 'Retry', skip: 'Skip', archive: 'Archive', restore: 'Restore', export: 'Export', import: 'Import', confirm: 'Confirm', previous: 'Previous', next: 'Next', close: 'Close', run: 'Run', add: 'Add', extract: 'Extract' },
  statuses: { IDLE: 'Idle', SCHEDULED: 'Scheduled', RUNNING: 'Running', PAUSED: 'Paused', STOPPED: 'Stopped', WAITING: 'Waiting', COMPLETED: 'Completed', FAILED: 'Failed', PENDING: 'Pending', OPENING: 'Opening', READY: 'Ready', PUBLISHING: 'Publishing', PUBLISHED: 'Published', PUBLISHED_UNVERIFIED: 'Published — Unverified', SKIPPED: 'Skipped', NOT_REQUIRED: 'Not required', CONNECTED: 'Connected', DISCONNECTED: 'Disconnected', OK: 'OK', WARN: 'Warning', FAIL: 'Failed' },
  errors: { dailyPostLimitReached: 'You have reached the daily post limit', unknown: 'An unexpected error occurred', invalidJson: 'Invalid JSON file', loginRequired: 'X login is required', publishControlsNotReady: 'Publishing controls are not ready' },
  settings: { title: 'Settings', interval: 'Interval in minutes', maxRetries: 'Maximum retry attempts', timezone: 'Time zone', duplicatePolicy: 'Duplicate policy', notifications: 'Enable important event notifications', confirmBeforeStart: 'Confirm before starting Queue', keepAutomationTabOpen: 'Keep automation tab open', closeTabOnComplete: 'Close tab when Queue completes', language: 'Language', globalDefaults: 'Global Defaults', workspaceOverride: 'Save as Workspace Override', clearOverride: 'Use Global Defaults' },
  operation: { title: 'Operation Dashboard', currentTweet: 'Current Tweet', publishingCenter: 'Publishing Control Center', published: 'Published', remaining: 'Remaining', failed: 'Failed', skipped: 'Skipped', startAt: 'Session starts at', nextTweetAfter: 'Next tweet after', currentItem: 'Current item', readyToRun: 'Ready to run', engineRunning: 'Engine is running', pausedHint: 'Queue is paused — press Resume to continue' },
  queue: { title: 'Queue', empty: 'No items match the current search.', pageSize: 'Items per page', selectPage: 'Select page items', selected: 'selected', clearCompleted: 'Clear Completed', item: 'item', items: 'items', page: 'Page', of: 'of', bank: 'Tweet Bank' },
  banks: { title: 'Tweet Banks', add: 'Add Bank', extract: 'Extract Selected', refreshDiff: 'Refresh & Diff', temporaryUrl: 'Temporary URL for an unsaved bank', noMatch: 'No banks match the current search.', active: 'Active', replace: 'Replace unprocessed items', append: 'Add new links only' },
  tests: { title: 'Startup Tests', validation: 'Startup Validation', preflight: 'Preflight Check', dryRun: 'Dry Run · No Post', runPreflight: 'Run Check', testFirst: 'Test First Item', testQueue: 'Test Entire Queue', stopTest: 'Stop Test', noPost: 'Checks the Composer and Post button without clicking it or increasing attempts' },
  analytics: { title: 'Analytics Dashboard', totalSessions: 'Total sessions', totalPosts: 'Total posts', published: 'Published', failed: 'Failed', skipped: 'Skipped', successRate: 'Success Rate', averageAttempts: 'Average attempts', duration: 'Average session duration', mostActiveBank: 'Most active bank', lastActivity: 'Last activity', allXpilot: 'All X-Pilot' },
  diagnostics: { title: 'Diagnostics Center', run: 'Run Diagnostics', readOnly: 'Read-only checks without publishing or changing data', extensionVersion: 'Extension version', storageSchema: 'Storage schema', activeWorkspace: 'Active Workspace', automationWorkspace: 'Automation Workspace', runningSession: 'Running Session', alarm: 'Alarm', automationTab: 'Automation Tab', completed: 'Read-only diagnostics completed — no post action was executed' },
  workspaces: { title: 'All Workspaces', active: 'Active Workspace', new: 'New Workspace', noDescription: 'No description', running: 'Running now', ready: 'Ready', lastActivity: 'Last activity' },
};
