import type { GlobalAnalytics, WorkspaceAnalytics } from '../../domain/analytics';
import type { Workspace } from '../../domain/models';

export function AnalyticsTab({ global, workspace, workspaceRows, workspaces, selectedWorkspaceId, onWorkspaceChange }: { global: GlobalAnalytics; workspace?: WorkspaceAnalytics; workspaceRows: WorkspaceAnalytics[]; workspaces: Workspace[]; selectedWorkspaceId: string; onWorkspaceChange: (value: string) => void }) {
  const formatDuration = (milliseconds: number) => { if (!milliseconds) return '—'; const minutes = Math.round(milliseconds / 60000); return minutes < 60 ? `${minutes} د` : `${Math.floor(minutes / 60)} س ${minutes % 60} د`; };
  const latest = workspace?.lastActivityAt ? new Date(workspace.lastActivityAt).toLocaleString('ar') : '—';
  const maxSessions = Math.max(1, ...global.sessionsOverTime.map((point) => point.sessions));
  return <section className="tab-panel analytics-panel" role="tabpanel" aria-label="التحليلات"><section className="card"><div className="section-heading"><div><span className="eyebrow">ANALYTICS DASHBOARD</span><h2>لوحة التحليلات</h2></div><select value={selectedWorkspaceId} onChange={(event) => onWorkspaceChange(event.target.value)} aria-label="نطاق التحليلات"><option value="*">كل X-Pilot</option>{workspaces.filter((item) => !item.archived).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><p className="muted">الحسابات مشتقة مباشرة من Sessions وHistory وQueue ولا يتم تخزين إحصاءات مكررة.</p></section>{workspace ? <><div className="analytics-grid"><Metric label="Total sessions" value={workspace.totalSessions} /><Metric label="Total posts" value={workspace.totalPosts} /><Metric label="Published" value={workspace.published} /><Metric label="Failed" value={workspace.failed} /><Metric label="Skipped" value={workspace.skipped} /><Metric label="Success Rate" value={`${workspace.successRate}%`} /><Metric label="Average attempts" value={workspace.averageAttempts || '—'} /><Metric label="Average session duration" value={formatDuration(workspace.averageSessionDurationMs)} /></div><section className="card analytics-detail"><div><strong>Most active bank</strong><span>{workspace.mostActiveBank ? `${workspace.mostActiveBank.name} · ${workspace.mostActiveBank.activity} عناصر` : '—'}</span></div><div><strong>Last activity</strong><span>{latest}</span></div></section></> : <><div className="analytics-grid"><Metric label="Total Workspaces" value={global.totalWorkspaces} /><Metric label="Total published" value={global.totalPublished} /><Metric label="Total failures" value={global.totalFailures} /><Metric label="Sessions over time" value={global.sessionsOverTime.reduce((sum, point) => sum + point.sessions, 0)} /></div><section className="card"><h3>مقارنة Workspaces</h3><div className="analytics-table">{workspaceRows.map((row) => <button key={row.workspaceId} className="analytics-table-row" onClick={() => onWorkspaceChange(row.workspaceId)}><strong>{row.workspaceName}</strong><span>{row.published} منشور</span><span>{row.failed} فشل</span><span>{row.successRate}% نجاح</span></button>)}{!workspaceRows.length && <p className="muted">لا توجد بيانات Analytics بعد.</p>}</div></section></>}<section className="card"><h3>Sessions over time</h3><div className="sessions-chart">{global.sessionsOverTime.map((point) => <div className="sessions-bar" key={point.date} title={`${point.date}: ${point.sessions}`}><span style={{ height: `${Math.max(8, (point.sessions / maxSessions) * 100)}%` }}></span><small>{point.date.slice(5)}</small></div>)}{!global.sessionsOverTime.length && <p className="muted">لا توجد جلسات مسجلة بعد.</p>}</div></section></section>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="analytics-metric"><span>{label}</span><strong>{value}</strong></div>; }
